# Generated by Django 6.0.2 on 2026-02-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
    ]
